MyShop/MyShop.WebUI/Controllers/BasketController.cs
using MyShop.Core.Contracts;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MyShop.WebUI.Controllers
{
    public class BasketController : Controller
    {
        IBasketService basketService;

        public BasketController(IBasketService BasketService)
        {
            this.basketService = BasketService;
        }

        // GET: Basket
        public ActionResult Index()
        {
            var model = basketService.GetBasketItem(this.HttpContext);
            return View(model);
        }

        public ActionResult AddToBasket(string Id)
        {
            basketService.AddToBasket(this.HttpContext, Id);

            return RedirectToAction("Index");
        }

        public ActionResult RemoveFromBasket(string Id)
        {
            basketService.RemoveFromBasket (this.HttpContext, Id);

            return RedirectToAction("Index");
        }

        public PartialViewResult BasketSummary()
        {
            var basketSummary = basketService.GetBasketSummary(this.HttpContext);

            return PartialView(basketSummary);
        }
    }
}

MyShop/MyShop.WebUI/Views/Basket/BasketSummary.cshtml
@model MyShop.Core.ViewModels.BasketSummaryViewModel

    <ul class="nav navbar-nav navbar-right">
        <li>
            <a href="@Url.Action("Index", "Basket")">@Model.BasketCount items</a>
        </li>
        <li>
            <a href="@Url.Action("Index", "Basket")">@String.Format("{0:c}", Model.BasketTotal) items</a>
        </li>
    </ul>

MyShop/MyShop.WebUI/Views/Basket/Index.cshtml
@model IEnumerable<MyShop.Core.ViewModels.BasketItemViewModel>

@{
    ViewBag.Title = "Basket";
}

<h2>Basket</h2>


<table class="table">
    <tr>
        <th></th>
        <th>
            @Html.DisplayNameFor(model => model.ProductName)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Quanity)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>

        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                <img style="height:50px" class="img" src="~/Content/ProductImage/@item.Image" />
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ProductName)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Quanity)
            </td>

            <td>
                @String.Format("{0:c}", item.Price)
            </td>
            <td>
                @String.Format("{0:c}", item.Price * item.Quanity)
            </td>
            <td>
                <a href="@Url.Action("RemoveFromBasket", "Basket", new { Id = item.Id } )" class="btn btn-danger">Delete</a>
            </td>
        </tr>


    }

    <tr>
        <td colspan="4" style="text-align:right">
            <strong>Basket Total</strong>
        </td>
        <td>
            @String.Format("{0:c}", (from p in Model select p.Price * p.Quanity).Sum())
        </td>
    </tr>

</table>